# Generated by Django 5.0.6 on 2024-07-03 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="Image",
            new_name="original_image",
        ),
    ]
